String domain = 'http://321tips.j19o.cn:8899/';
String vlcDomain = '10.220.8.242/share/';
String imgDomain = 'http://321tips.j19o.cn:8899/';
String cateId = '7';
String vlcStart = 'smb://root:qwe123qwe@';
void setDomain(String str){domain=str;}
void setVlc(String str){vlcDomain=str;}
void setImg(String str){imgDomain=str;}
void setCateId(String str){cateId=str;}
void setVlcStart(String str){vlcStart=str;}